### ISSUE TITLE
'tensorboard.summary._tf.summary' has no attribute 'tensor_summary'

### ISSUE THREAD

**Issue by dgriffiths3** [tensorflow/graphics#3]
Just trying a basic example of the 3D tensorboard for a point cloud.

tensorflow == 2.0.0-alpha0
tensorboard == 1.14.0a20190509 (tb-nightly)
python == 3.7.3
os == MacOS 10.14.4

Code to recreate:

```
import tensorflow as tf
import numpy as np

from tensorboard.plugins.mesh import summary as mesh_summary

point_cloud = np.random.rand(1, 1064, 3)
point_colors = np.random.randint(0, 255, (1, 1064, 3))

point_cloud = tf.constant(point_cloud)
point_colors = tf.constant(point_colors)

summary = mesh_summary.op('point_cloud', vertices=point_cloud, colors=point_colors)
```

Error:

```
Traceback (most recent call last):
  File "/Users/david/Desktop/tensorboard3d/tb_test.py", line 12, in <module>
    summary = mesh_summary.op('point_cloud', vertices=point_cloud, colors=point_colors)
  File "/usr/local/lib/python3.7/site-packages/tensorboard/plugins/mesh/summary.py", line 123, in op
    content_type, json_config, collections))
  File "/usr/local/lib/python3.7/site-packages/tensorboard/plugins/mesh/summary.py", line 59, in _get_tensor_summary
    tensor_summary = tf.summary.tensor_summary(
AttributeError: module 'tensorboard.summary._tf.summary' has no attribute 'tensor_summary'

```

Do I need a specific version of tensorboard for this?

**Comment by podlipensky** [comment]
Yes, you need to install tb-nightly which may require tf-nightly. So the best way is to get rid of tensorflow and install tf-nightly (which contains tb-nightly). See our colab for exact instructions: https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/mesh/Mesh_Plugin_Tensorboard.ipynb

**Comment by dgriffiths3** [comment]
I've installed `tb-nightly` but this doesn't work with `tensorflow== 2.0.0-alpha0`. `tf-nightly` is version `1.14`, so will this not work with `2.X`?

**Comment by podlipensky** [comment]
We do not support TF2 just yet.
