### ISSUE TITLE
mesh summary support for tensorflow 2

### ISSUE THREAD

**Issue by PgLoLo** [tensorflow/graphics#81]
Does mesh summary supports tensorflow 2.0.0?

Right now I am getting this error while trying to add mesh summary:

```
AttributeError: module 'tensorboard.summary._tf.summary' has no attribute 'tensor_summary'
```

Code to reproduce:
```
import tensorflow as tf
from tensorboard.plugins.mesh import summary as mesh_summary

writer = tf.summary.create_file_writer("./logs")
with writer.as_default(), tf.device("cpu:0"):
    mesh_summary.op('mesh', [[[0, 0, 0], [0, 1, 0], [1, 0, 0]]], [[0, 1, 2]])
```

**Comment by podlipensky** [comment]
Will look into this.

**Comment by podlipensky** [comment]
I got different error: Merging tf.summary.* ops is not compatible with eager execution.
As for now the plugin doesn't support Eager execution. But it still works with TF2.0.

**Comment by geromidg** [comment]
It seems as of https://github.com/tensorflow/tensorboard/commit/fbfaa250d724c387edc6aa3bb5fdb0175eed16b4 there is support for TF 2.0.

Just change
- `from tensorboard.plugins.mesh import summary` to `from tensorboard.plugins.mesh import summary_v2`
- `mesh_summary.op()` to `mesh_summary.mesh()`

The following is working with TF 2.0.0 and TB 2.0.2 for me.

```
import tensorflow as tf
from tensorboard.plugins.mesh import summary_v2 as mesh_summary

writer = tf.summary.create_file_writer("logs")
with writer.as_default():
    mesh_summary.mesh('mesh', tf.random.uniform((1, 1000, 3)), step=0)
    writer.flush()
```

**Comment by julienvalentin** [comment]
Closing as it seems that things are working as intended

**Comment by topinfrassi01** [comment]
It does work as intended, but the documentation isn't updated to reflect this change : https://www.tensorflow.org/graphics/tensorboard

It's currently pretty much impossible to know about this change unless you stumble upon this issue.
